"""empty message

Revision ID: c6d40ca719b3
Revises: None
Create Date: 2017-04-26 13:24:02.863381

"""

# revision identifiers, used by Alembic.
revision = 'c6d40ca719b3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
